
services:
  suffcal:
    image: ghcr.io/floskinner/suffcal:latest
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - ./downloads:/app/downloads
    environment:
      - INSTA_TARGET_USER=fest_in_aussicht
      - INSTA_USER=${INSTA_USER}
      - INSTA_PASSWORD=${INSTA_PASSWORD}
      - INSTA_UPDATE_INTERVAL=240

      - CALENDAR_USER=${CALENDAR_USER}
      - CALENDAR_PASSWORD=${CALENDAR_PASSWORD}
      - CALENDAR_URL=${CALENDAR_URL}
      - CALENDAR_NAME=Partys

      # - HF_TOKEN=${HF_TOKEN} (Optional, only needed if you somehow deleted the included models or want to change them)
